sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION test

scala:
  - 2.13.1

jdk:
  - openjdk8

